# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment
mc_version=1.20.1
mc_version_range=[1.20.1]
neo_version=47.1.70
neo_version_range=[47.1.0,)
loader_version_range=[47,)
mappings_channel=sugarcane
mappings_version=2023.08.20-1.20.1

# Mod
mod_id=aether_gloves_for_all
mod_group=krelox.gloves_for_all
mod_name=Gloves For All
mod_version=1.20.1-2.1.0-neoforge
mod_license=Assets: All Rights Reserved; Code: LGPL-3.0
mod_url=https://modrinth.com/mod/aether-gloves-for-all
mod_github=https://github.com/KreloX/Gloves-For-All
mod_credits=The Aether Team
mod_authors=KreloX
mod_description=Adds gloves for selected other mods' materials, improving parity of sets and their abilities with The Aether.

# Dependencies
aether_version=1.20.1-1.2.0-neoforge
nitrogen_version=1.20.1-0.1.2-neoforge
curios_version=5.7.0

mixin_version=0.12.11+mixin.0.8.5
mixinbooster_version=0.1.3+1.20.1
mixinextras_version=0.5.3
mixinsquared_version=0.3.7-beta.1

emi_version=1.1.20+1.20.1
rei_version=12.1.785
cloth_config_version=11.1.136
architectury_version=9.2.14

embeddium_version=0.3.31+mc1.20.1

caverns_and_chasms_version=2.1.0
    gallery_version=1.0.3
savage_and_ravage_version=6.0.0
oreganized_version=4.3.0
    multikulti_version=1.20.1-1.0.4
    blueprint_version=7.1.3
galosphere_version=1.20.1-1.5.0
addadd_version=r8V0VbWA
simpleores_version=1.20.1-6.0.0.3
    bucketlib_version=1.20.1-2.3.5.3
    simplecorelib_version=1.20.1-6.0.1.2

undergarden_version=0.8.14
blue_skies_version=1.3.31
    structure_gel_version=2.16.2
voidscape_version=1.20.1-1.5.389
midnight_version=0.6.7
    lucent_version=1.5.5
    smartbrainlib_version=EPH5uBb1
deeperdarker_version=1.3.3-forge+1.20.1

botania_version=1.20.1-447-forge
    patchouli_version=1.20.1-84.1-forge

create_version=mc1.20.1-6.0.8
    create_repair_version=m4xKS8Xh
    registrate_version=1.20-1.3.11
redstone_arsenal_version=8.0.1
thermal_cultivation_version=11.0.1
thermal_innovation_version=11.0.1
tools_complement_version=4.0.0.25
thermal_extra_version=3.2.6-1.20.1
    thermal_foundation_version=11.0.6
    thermal_core_version=11.0.7
    cofh_core_version=11.0.2
mekanism_version=1.20.1-10.4.9.61

iceandfire_version=2.1.13-1.20.1-beta-5
    citadel_version=2.6.2

# Publishing
curseforge_id=
modrinth_id=
version_type=release
