modLoader = "javafml"
loaderVersion = "$loader_version_range"
license = "$mod_license"
issueTrackerURL= "$mod_github/issues"

[[mods]]
modId = "$mod_id"
version = "$mod_version"
displayName = "$mod_name"
updateJSONURL= "$mod_github/raw/$mc_version-develop/update.json"
displayURL = "$mod_url"
logoFile = "${mod_id}.png"
credits = "$mod_credits"
authors = "$mod_authors"
description = '''$mod_description'''

[[dependencies.$mod_id]]
    modId = "forge"
    mandatory = true
    versionRange = "$neo_version_range"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "aether"
    mandatory = true
    versionRange = "[$aether_version,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "minecraft"
    mandatory = true
    versionRange = "$mc_version_range"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.$mod_id]]
    modId = "caverns_and_chasms"
    mandatory = false
    versionRange = "[2.1.0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "savage_and_ravage"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "oreganized"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "galosphere"
    mandatory = false
    versionRange = "[1.5.0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "additionaladditions"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "simpleores"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "undergarden"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "blue_skies"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "voidscape"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "midnight"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "deeperdarker"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "botania"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "create"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "redstone_arsenal"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "tools_complement"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "thermal"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "thermal_extra"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "mekanismtools"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.$mod_id]]
    modId = "iceandfire"
    mandatory = false
    versionRange = "1"
    ordering = "AFTER"
    side = "BOTH"