@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package krelox.gloves_for_all;

import com.mojang.math.FieldsAreNonnullByDefault;
import com.mojang.math.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;